import {MigrationInterface, QueryRunner} from "typeorm";

export class InitialEntities1639058754550 implements MigrationInterface {
    name = 'InitialEntities1639058754550'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "attachment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "url" character varying NOT NULL, "contentId" uuid, CONSTRAINT "PK_d2a80c3a8d467f08a750ac4b420" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "doubt" ("id" SERIAL NOT NULL, "description" character varying NOT NULL, "status" boolean NOT NULL, "createdAt" TIMESTAMP NOT NULL, "studentId" uuid, "studentEmail" character varying, "contentId" uuid, CONSTRAINT "PK_8f23d800a75d09d4e139a40b998" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "duel" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "maxGroupParts" integer NOT NULL, "studentId" uuid, "studentEmail" character varying, CONSTRAINT "PK_1575a4255b3bdf1f11398841d0d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "chat" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL, CONSTRAINT "PK_9d0b2ba74336710fd31154738a5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "message" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" character varying NOT NULL, "createdAt" character varying NOT NULL, CONSTRAINT "PK_ba01f0a3e0123651915008bc578" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stud_teach_message" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" character varying NOT NULL, "createdAt" character varying NOT NULL, "chatId" integer, "studentId" uuid, "studentEmail" character varying, CONSTRAINT "PK_3a9438a29a4224580bf266d5cfd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teach_stud_message" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" character varying NOT NULL, "createdAt" character varying NOT NULL, "chatId" integer, "teacherId" uuid, "teacherEmail" character varying, CONSTRAINT "PK_b4b9d3a98b8efa33f4984733323" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stud_teach_chat" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL, "studentId" uuid, "studentEmail" character varying, "teacherId" uuid, "teacherEmail" character varying, CONSTRAINT "PK_58cf3973983b8def64d482c57de" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "unity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "subjectId" uuid, CONSTRAINT "PK_bd68d5ab918eab83daa1203032f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subject" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "schoolGradeId" uuid, CONSTRAINT "PK_12eee115462e38d62e5455fc054" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "school_grade" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "index" integer NOT NULL, "teachingTypeId" uuid, CONSTRAINT "PK_eae314198c548c010a720c875e9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teaching_type" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, CONSTRAINT "PK_d976c2a8ea85fac42049a718abe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teach_teach_message" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" character varying NOT NULL, "createdAt" character varying NOT NULL, "teacherId" uuid, "teacherEmail" character varying, "chatId" integer, CONSTRAINT "PK_5b4415a7cf10ce743bf4223e665" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teach_teach_chat" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL, "teacherOneId" uuid, "teacherOneEmail" character varying, "teacherTwoId" uuid, "teacherTwoEmail" character varying, CONSTRAINT "PK_c71249298bfabf98570d00aaaaf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "name" character varying NOT NULL, "profilePicture" character varying NOT NULL, "password" character varying NOT NULL, "isOnline" boolean NOT NULL, CONSTRAINT "PK_95c07c16136adcfdcb8221c1fc9" PRIMARY KEY ("id", "email"))`);
        await queryRunner.query(`CREATE TABLE "teacher" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "name" character varying NOT NULL, "profilePicture" character varying NOT NULL, "password" character varying NOT NULL, "isOnline" boolean NOT NULL, "teachingTypeId" uuid, CONSTRAINT "PK_5c0837a4bd45afb3ca779026d10" PRIMARY KEY ("id", "email"))`);
        await queryRunner.query(`CREATE TABLE "interative_room" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "teacherId" uuid, "teacherEmail" character varying, CONSTRAINT "PK_902f9a56045e9dad97c2ccd5929" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stud_stud_message" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" character varying NOT NULL, "createdAt" character varying NOT NULL, "studentId" uuid, "studentEmail" character varying, "chatId" integer, CONSTRAINT "PK_fad5982a7786ffc9c8cbb80c4b7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stud_stud_chat" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL, "studentOneId" uuid, "studentOneEmail" character varying, "studentTwoId" uuid, "studentTwoEmail" character varying, CONSTRAINT "PK_ffdaab2f1e6632119ccef28ff4d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "student" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "name" character varying NOT NULL, "profilePicture" character varying NOT NULL, "password" character varying NOT NULL, "isOnline" boolean NOT NULL, "teachingTypeId" uuid, CONSTRAINT "PK_78f0656779bd27e868856e6eb89" PRIMARY KEY ("id", "email"))`);
        await queryRunner.query(`CREATE TABLE "content_review" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL, "studentId" uuid, "studentEmail" character varying, CONSTRAINT "PK_76988fae19e2a3d89ba01bde674" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "content" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" character varying NOT NULL, "video" character varying NOT NULL, "index" integer NOT NULL, "unityId" uuid, CONSTRAINT "PK_6a2083913f3647b44f205204e36" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "question" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "description" character varying NOT NULL, "difficulty" integer NOT NULL, "index" character varying NOT NULL, "contentId" uuid, CONSTRAINT "PK_21e5786aa0ea704ae185a79b2d5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "alternative" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "description" character varying NOT NULL, "index" integer NOT NULL, "questionId" uuid, CONSTRAINT "PK_93e717011957def707e61de0723" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "duel_students_student" ("duelId" uuid NOT NULL, "studentId" uuid NOT NULL, "studentEmail" character varying NOT NULL, CONSTRAINT "PK_e0d9a0d2e12322f7086b80c049c" PRIMARY KEY ("duelId", "studentId", "studentEmail"))`);
        await queryRunner.query(`CREATE INDEX "IDX_75ecde94f7707a5840b2f84836" ON "duel_students_student" ("duelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_102ce82622940bbac08376f94b" ON "duel_students_student" ("studentId", "studentEmail") `);
        await queryRunner.query(`CREATE TABLE "duel_questions_question" ("duelId" uuid NOT NULL, "questionId" uuid NOT NULL, CONSTRAINT "PK_a46619ab722b931ff8da8606f54" PRIMARY KEY ("duelId", "questionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_422be4edd69d21b67cde6c379d" ON "duel_questions_question" ("duelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8181c4d50660730da4802f3fd2" ON "duel_questions_question" ("questionId") `);
        await queryRunner.query(`CREATE TABLE "interative_room_teachers_teacher" ("interativeRoomId" uuid NOT NULL, "teacherId" uuid NOT NULL, "teacherEmail" character varying NOT NULL, CONSTRAINT "PK_b4f2814cc9b1d619045bfe3a8b9" PRIMARY KEY ("interativeRoomId", "teacherId", "teacherEmail"))`);
        await queryRunner.query(`CREATE INDEX "IDX_99247eb0d041dac5dff873ce1b" ON "interative_room_teachers_teacher" ("interativeRoomId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2f4e01a82d900b2afdce689ce8" ON "interative_room_teachers_teacher" ("teacherId", "teacherEmail") `);
        await queryRunner.query(`CREATE TABLE "interative_room_students_student" ("interativeRoomId" uuid NOT NULL, "studentId" uuid NOT NULL, "studentEmail" character varying NOT NULL, CONSTRAINT "PK_c0bdaa3618395d4494885ce3a02" PRIMARY KEY ("interativeRoomId", "studentId", "studentEmail"))`);
        await queryRunner.query(`CREATE INDEX "IDX_775a6fcd97e1d308eaea34a8aa" ON "interative_room_students_student" ("interativeRoomId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9c508d33d465acfbcb06f5198d" ON "interative_room_students_student" ("studentId", "studentEmail") `);
        await queryRunner.query(`CREATE TABLE "interative_room_questions_question" ("interativeRoomId" uuid NOT NULL, "questionId" uuid NOT NULL, CONSTRAINT "PK_63549b7b8ce48e6d5fc4bc69fb2" PRIMARY KEY ("interativeRoomId", "questionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4e2cd85136840150f6fc367459" ON "interative_room_questions_question" ("interativeRoomId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6c7221dde585ad26b925e2f4ee" ON "interative_room_questions_question" ("questionId") `);
        await queryRunner.query(`CREATE TABLE "content_review_contents_content" ("contentReviewId" uuid NOT NULL, "contentId" uuid NOT NULL, CONSTRAINT "PK_5b937c7da8baa45aeefb6622e03" PRIMARY KEY ("contentReviewId", "contentId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_087fe9fdd8e15ce9ae3221f0ba" ON "content_review_contents_content" ("contentReviewId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d148cfdb8c8da174a641df0931" ON "content_review_contents_content" ("contentId") `);
        await queryRunner.query(`ALTER TABLE "attachment" ADD CONSTRAINT "FK_bba44fec71adc588b9f4136105f" FOREIGN KEY ("contentId") REFERENCES "content"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "doubt" ADD CONSTRAINT "FK_d3911d53f3e4364246872f2213f" FOREIGN KEY ("studentId", "studentEmail") REFERENCES "student"("id","email") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "doubt" ADD CONSTRAINT "FK_24a6551ef4d2649af7a387941b6" FOREIGN KEY ("contentId") REFERENCES "content"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "duel" ADD CONSTRAINT "FK_577c8cacbb5008013870738527c" FOREIGN KEY ("studentId", "studentEmail") REFERENCES "student"("id","email") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "stud_teach_message" ADD CONSTRAINT "FK_531b6bd6ea9096ffb588f44faf3" FOREIGN KEY ("chatId") REFERENCES "stud_teach_chat"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "stud_teach_message" ADD CONSTRAINT "FK_90f9a73a84ec392b1aa97268956" FOREIGN KEY ("studentId", "studentEmail") REFERENCES "student"("id","email") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "teach_stud_message" ADD CONSTRAINT "FK_55be4f8374eb9650f5a513e62d3" FOREIGN KEY ("chatId") REFERENCES "stud_teach_chat"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "teach_stud_message" ADD CONSTRAINT "FK_a9cc6156741c1552f10f34ee052" FOREIGN KEY ("teacherId", "teacherEmail") REFERENCES "teacher"("id","email") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "stud_teach_chat" ADD CONSTRAINT "FK_efd8e9d88076a2bb009d87a281a" FOREIGN KEY ("studentId", "studentEmail") REFERENCES "student"("id","email") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "stud_teach_chat" ADD CONSTRAINT "FK_768b418e3ac640e4bd23cc62c4d" FOREIGN KEY ("teacherId", "teacherEmail") REFERENCES "teacher"("id","email") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "unity" ADD CONSTRAINT "FK_c8c6acef92752b428d651516920" FOREIGN KEY ("subjectId") REFERENCES "subject"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "subject" ADD CONSTRAINT "FK_ce164c28fa601e77c850a18254b" FOREIGN KEY ("schoolGradeId") REFERENCES "school_grade"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "school_grade" ADD CONSTRAINT "FK_63d5d0cf569c2acbfeadf78bc6b" FOREIGN KEY ("teachingTypeId") REFERENCES "teaching_type"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "teach_teach_message" ADD CONSTRAINT "FK_ad5bc9c60d4c7d26f7d33643a9a" FOREIGN KEY ("teacherId", "teacherEmail") REFERENCES "teacher"("id","email") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "teach_teach_message" ADD CONSTRAINT "FK_779143e45ba9a5401ec311432e1" FOREIGN KEY ("chatId") REFERENCES "teach_teach_chat"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "teach_teach_chat" ADD CONSTRAINT "FK_9c6da0c4ea57d4a9f56f6e6cf4c" FOREIGN KEY ("teacherOneId", "teacherOneEmail") REFERENCES "teacher"("id","email") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "teach_teach_chat" ADD CONSTRAINT "FK_875dedc94739e8d468baa86eff9" FOREIGN KEY ("teacherTwoId", "teacherTwoEmail") REFERENCES "teacher"("id","email") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "teacher" ADD CONSTRAINT "FK_604fe325d9a0a93e52d5c8758b5" FOREIGN KEY ("teachingTypeId") REFERENCES "teaching_type"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "interative_room" ADD CONSTRAINT "FK_42f14f6baaaf4a2fecfe966a861" FOREIGN KEY ("teacherId", "teacherEmail") REFERENCES "teacher"("id","email") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "stud_stud_message" ADD CONSTRAINT "FK_25cc9d4a3573bdf01fa891dd9ee" FOREIGN KEY ("studentId", "studentEmail") REFERENCES "student"("id","email") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "stud_stud_message" ADD CONSTRAINT "FK_867a6c29465030d75779287e82b" FOREIGN KEY ("chatId") REFERENCES "stud_stud_chat"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "stud_stud_chat" ADD CONSTRAINT "FK_da7002ef988a3190dc321fbeb94" FOREIGN KEY ("studentOneId", "studentOneEmail") REFERENCES "student"("id","email") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "stud_stud_chat" ADD CONSTRAINT "FK_cced166e355d31f17072a490f85" FOREIGN KEY ("studentTwoId", "studentTwoEmail") REFERENCES "student"("id","email") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "student" ADD CONSTRAINT "FK_dcc9a6fa13769727b2df315f5eb" FOREIGN KEY ("teachingTypeId") REFERENCES "teaching_type"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "content_review" ADD CONSTRAINT "FK_84f288e37d4dc0d95d8098deda4" FOREIGN KEY ("studentId", "studentEmail") REFERENCES "student"("id","email") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "content" ADD CONSTRAINT "FK_d553a9a07bbb76b508eb19f2b0f" FOREIGN KEY ("unityId") REFERENCES "unity"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "question" ADD CONSTRAINT "FK_f7cc42568ef88190783fbaf4274" FOREIGN KEY ("contentId") REFERENCES "content"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "alternative" ADD CONSTRAINT "FK_987e598dc6447a20fa182141434" FOREIGN KEY ("questionId") REFERENCES "question"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "duel_students_student" ADD CONSTRAINT "FK_75ecde94f7707a5840b2f84836f" FOREIGN KEY ("duelId") REFERENCES "duel"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "duel_students_student" ADD CONSTRAINT "FK_102ce82622940bbac08376f94bf" FOREIGN KEY ("studentId", "studentEmail") REFERENCES "student"("id","email") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "duel_questions_question" ADD CONSTRAINT "FK_422be4edd69d21b67cde6c379d8" FOREIGN KEY ("duelId") REFERENCES "duel"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "duel_questions_question" ADD CONSTRAINT "FK_8181c4d50660730da4802f3fd2f" FOREIGN KEY ("questionId") REFERENCES "question"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "interative_room_teachers_teacher" ADD CONSTRAINT "FK_99247eb0d041dac5dff873ce1bb" FOREIGN KEY ("interativeRoomId") REFERENCES "interative_room"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "interative_room_teachers_teacher" ADD CONSTRAINT "FK_2f4e01a82d900b2afdce689ce83" FOREIGN KEY ("teacherId", "teacherEmail") REFERENCES "teacher"("id","email") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "interative_room_students_student" ADD CONSTRAINT "FK_775a6fcd97e1d308eaea34a8aa9" FOREIGN KEY ("interativeRoomId") REFERENCES "interative_room"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "interative_room_students_student" ADD CONSTRAINT "FK_9c508d33d465acfbcb06f5198d2" FOREIGN KEY ("studentId", "studentEmail") REFERENCES "student"("id","email") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "interative_room_questions_question" ADD CONSTRAINT "FK_4e2cd85136840150f6fc3674594" FOREIGN KEY ("interativeRoomId") REFERENCES "interative_room"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "interative_room_questions_question" ADD CONSTRAINT "FK_6c7221dde585ad26b925e2f4ee8" FOREIGN KEY ("questionId") REFERENCES "question"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "content_review_contents_content" ADD CONSTRAINT "FK_087fe9fdd8e15ce9ae3221f0ba0" FOREIGN KEY ("contentReviewId") REFERENCES "content_review"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "content_review_contents_content" ADD CONSTRAINT "FK_d148cfdb8c8da174a641df09319" FOREIGN KEY ("contentId") REFERENCES "content"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "content_review_contents_content" DROP CONSTRAINT "FK_d148cfdb8c8da174a641df09319"`);
        await queryRunner.query(`ALTER TABLE "content_review_contents_content" DROP CONSTRAINT "FK_087fe9fdd8e15ce9ae3221f0ba0"`);
        await queryRunner.query(`ALTER TABLE "interative_room_questions_question" DROP CONSTRAINT "FK_6c7221dde585ad26b925e2f4ee8"`);
        await queryRunner.query(`ALTER TABLE "interative_room_questions_question" DROP CONSTRAINT "FK_4e2cd85136840150f6fc3674594"`);
        await queryRunner.query(`ALTER TABLE "interative_room_students_student" DROP CONSTRAINT "FK_9c508d33d465acfbcb06f5198d2"`);
        await queryRunner.query(`ALTER TABLE "interative_room_students_student" DROP CONSTRAINT "FK_775a6fcd97e1d308eaea34a8aa9"`);
        await queryRunner.query(`ALTER TABLE "interative_room_teachers_teacher" DROP CONSTRAINT "FK_2f4e01a82d900b2afdce689ce83"`);
        await queryRunner.query(`ALTER TABLE "interative_room_teachers_teacher" DROP CONSTRAINT "FK_99247eb0d041dac5dff873ce1bb"`);
        await queryRunner.query(`ALTER TABLE "duel_questions_question" DROP CONSTRAINT "FK_8181c4d50660730da4802f3fd2f"`);
        await queryRunner.query(`ALTER TABLE "duel_questions_question" DROP CONSTRAINT "FK_422be4edd69d21b67cde6c379d8"`);
        await queryRunner.query(`ALTER TABLE "duel_students_student" DROP CONSTRAINT "FK_102ce82622940bbac08376f94bf"`);
        await queryRunner.query(`ALTER TABLE "duel_students_student" DROP CONSTRAINT "FK_75ecde94f7707a5840b2f84836f"`);
        await queryRunner.query(`ALTER TABLE "alternative" DROP CONSTRAINT "FK_987e598dc6447a20fa182141434"`);
        await queryRunner.query(`ALTER TABLE "question" DROP CONSTRAINT "FK_f7cc42568ef88190783fbaf4274"`);
        await queryRunner.query(`ALTER TABLE "content" DROP CONSTRAINT "FK_d553a9a07bbb76b508eb19f2b0f"`);
        await queryRunner.query(`ALTER TABLE "content_review" DROP CONSTRAINT "FK_84f288e37d4dc0d95d8098deda4"`);
        await queryRunner.query(`ALTER TABLE "student" DROP CONSTRAINT "FK_dcc9a6fa13769727b2df315f5eb"`);
        await queryRunner.query(`ALTER TABLE "stud_stud_chat" DROP CONSTRAINT "FK_cced166e355d31f17072a490f85"`);
        await queryRunner.query(`ALTER TABLE "stud_stud_chat" DROP CONSTRAINT "FK_da7002ef988a3190dc321fbeb94"`);
        await queryRunner.query(`ALTER TABLE "stud_stud_message" DROP CONSTRAINT "FK_867a6c29465030d75779287e82b"`);
        await queryRunner.query(`ALTER TABLE "stud_stud_message" DROP CONSTRAINT "FK_25cc9d4a3573bdf01fa891dd9ee"`);
        await queryRunner.query(`ALTER TABLE "interative_room" DROP CONSTRAINT "FK_42f14f6baaaf4a2fecfe966a861"`);
        await queryRunner.query(`ALTER TABLE "teacher" DROP CONSTRAINT "FK_604fe325d9a0a93e52d5c8758b5"`);
        await queryRunner.query(`ALTER TABLE "teach_teach_chat" DROP CONSTRAINT "FK_875dedc94739e8d468baa86eff9"`);
        await queryRunner.query(`ALTER TABLE "teach_teach_chat" DROP CONSTRAINT "FK_9c6da0c4ea57d4a9f56f6e6cf4c"`);
        await queryRunner.query(`ALTER TABLE "teach_teach_message" DROP CONSTRAINT "FK_779143e45ba9a5401ec311432e1"`);
        await queryRunner.query(`ALTER TABLE "teach_teach_message" DROP CONSTRAINT "FK_ad5bc9c60d4c7d26f7d33643a9a"`);
        await queryRunner.query(`ALTER TABLE "school_grade" DROP CONSTRAINT "FK_63d5d0cf569c2acbfeadf78bc6b"`);
        await queryRunner.query(`ALTER TABLE "subject" DROP CONSTRAINT "FK_ce164c28fa601e77c850a18254b"`);
        await queryRunner.query(`ALTER TABLE "unity" DROP CONSTRAINT "FK_c8c6acef92752b428d651516920"`);
        await queryRunner.query(`ALTER TABLE "stud_teach_chat" DROP CONSTRAINT "FK_768b418e3ac640e4bd23cc62c4d"`);
        await queryRunner.query(`ALTER TABLE "stud_teach_chat" DROP CONSTRAINT "FK_efd8e9d88076a2bb009d87a281a"`);
        await queryRunner.query(`ALTER TABLE "teach_stud_message" DROP CONSTRAINT "FK_a9cc6156741c1552f10f34ee052"`);
        await queryRunner.query(`ALTER TABLE "teach_stud_message" DROP CONSTRAINT "FK_55be4f8374eb9650f5a513e62d3"`);
        await queryRunner.query(`ALTER TABLE "stud_teach_message" DROP CONSTRAINT "FK_90f9a73a84ec392b1aa97268956"`);
        await queryRunner.query(`ALTER TABLE "stud_teach_message" DROP CONSTRAINT "FK_531b6bd6ea9096ffb588f44faf3"`);
        await queryRunner.query(`ALTER TABLE "duel" DROP CONSTRAINT "FK_577c8cacbb5008013870738527c"`);
        await queryRunner.query(`ALTER TABLE "doubt" DROP CONSTRAINT "FK_24a6551ef4d2649af7a387941b6"`);
        await queryRunner.query(`ALTER TABLE "doubt" DROP CONSTRAINT "FK_d3911d53f3e4364246872f2213f"`);
        await queryRunner.query(`ALTER TABLE "attachment" DROP CONSTRAINT "FK_bba44fec71adc588b9f4136105f"`);
        await queryRunner.query(`DROP INDEX "IDX_d148cfdb8c8da174a641df0931"`);
        await queryRunner.query(`DROP INDEX "IDX_087fe9fdd8e15ce9ae3221f0ba"`);
        await queryRunner.query(`DROP TABLE "content_review_contents_content"`);
        await queryRunner.query(`DROP INDEX "IDX_6c7221dde585ad26b925e2f4ee"`);
        await queryRunner.query(`DROP INDEX "IDX_4e2cd85136840150f6fc367459"`);
        await queryRunner.query(`DROP TABLE "interative_room_questions_question"`);
        await queryRunner.query(`DROP INDEX "IDX_9c508d33d465acfbcb06f5198d"`);
        await queryRunner.query(`DROP INDEX "IDX_775a6fcd97e1d308eaea34a8aa"`);
        await queryRunner.query(`DROP TABLE "interative_room_students_student"`);
        await queryRunner.query(`DROP INDEX "IDX_2f4e01a82d900b2afdce689ce8"`);
        await queryRunner.query(`DROP INDEX "IDX_99247eb0d041dac5dff873ce1b"`);
        await queryRunner.query(`DROP TABLE "interative_room_teachers_teacher"`);
        await queryRunner.query(`DROP INDEX "IDX_8181c4d50660730da4802f3fd2"`);
        await queryRunner.query(`DROP INDEX "IDX_422be4edd69d21b67cde6c379d"`);
        await queryRunner.query(`DROP TABLE "duel_questions_question"`);
        await queryRunner.query(`DROP INDEX "IDX_102ce82622940bbac08376f94b"`);
        await queryRunner.query(`DROP INDEX "IDX_75ecde94f7707a5840b2f84836"`);
        await queryRunner.query(`DROP TABLE "duel_students_student"`);
        await queryRunner.query(`DROP TABLE "alternative"`);
        await queryRunner.query(`DROP TABLE "question"`);
        await queryRunner.query(`DROP TABLE "content"`);
        await queryRunner.query(`DROP TABLE "content_review"`);
        await queryRunner.query(`DROP TABLE "student"`);
        await queryRunner.query(`DROP TABLE "stud_stud_chat"`);
        await queryRunner.query(`DROP TABLE "stud_stud_message"`);
        await queryRunner.query(`DROP TABLE "interative_room"`);
        await queryRunner.query(`DROP TABLE "teacher"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "teach_teach_chat"`);
        await queryRunner.query(`DROP TABLE "teach_teach_message"`);
        await queryRunner.query(`DROP TABLE "teaching_type"`);
        await queryRunner.query(`DROP TABLE "school_grade"`);
        await queryRunner.query(`DROP TABLE "subject"`);
        await queryRunner.query(`DROP TABLE "unity"`);
        await queryRunner.query(`DROP TABLE "stud_teach_chat"`);
        await queryRunner.query(`DROP TABLE "teach_stud_message"`);
        await queryRunner.query(`DROP TABLE "stud_teach_message"`);
        await queryRunner.query(`DROP TABLE "message"`);
        await queryRunner.query(`DROP TABLE "chat"`);
        await queryRunner.query(`DROP TABLE "duel"`);
        await queryRunner.query(`DROP TABLE "doubt"`);
        await queryRunner.query(`DROP TABLE "attachment"`);
    }

}
